---
- name: Detect SteamOS
  ansible.builtin.stat:
    path: /etc/steamos-release
  register: steamos_release

- name: Install fonts (macOS)
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install fonts (Linux)
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != 'Darwin'
