---
- name: Install fontconfig and unzip (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - fontconfig
      - unzip
    state: present
    update_cache: true
  when: ansible_os_family == 'Archlinux' and ansible_distribution != 'SteamOS'

- name: Install fontconfig and unzip (Debian/Ubuntu)
  become: "{{ ansible_distribution != 'SteamOS' }}"
  ansible.builtin.apt:
    name:
      - fontconfig
      - unzip
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian' and ansible_distribution != 'SteamOS'


- name: Create ~/.local/share/fonts directory
  become: false
  ansible.builtin.file:
    path: ~/.local/share/fonts
    state: directory
    recurse: true

- name: Download and install Nerd Fonts
  become: false
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerd_fonts_version }}/{{ item.name }}.zip"
    dest: ~/.local/share/fonts
    remote_src: true
    creates: "~/.local/share/fonts/{{ item.creates }}"
  loop: "{{ nerd_fonts }}"
  notify: Fc-cache
